"""Build metadata for the finish-release sync pull request."""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


TARGET_BASE_BY_RELEASE_BASE = {
    "main": "development",
    "support/v0": "development-v0",
}


@dataclass(frozen=True)
class FinishReleaseSync:
    target_base: str
    branch_name: str
    pr_title: str
    pr_body: str


def build_finish_release_sync(version_number: str, release_base_ref: str) -> FinishReleaseSync:
    try:
        target_base = TARGET_BASE_BY_RELEASE_BASE[release_base_ref]
    except KeyError as error:
        supported_refs = ", ".join(sorted(TARGET_BASE_BY_RELEASE_BASE))
        raise ValueError(
            f"Unsupported release base ref '{release_base_ref}'. Expected one of: {supported_refs}."
        ) from error

    branch_name = f"finish-release/v{version_number}-sync-{target_base}"
    return FinishReleaseSync(
        target_base=target_base,
        branch_name=branch_name,
        pr_title=f"Finish release {version_number}",
        pr_body=(
            f"Finish release {version_number}\n\n"
            "This PR is generated by the Finish Release Train workflow.\n\n"
            f"The `{branch_name}` branch is automation-owned and may be rewritten when "
            "the workflow is rerun. Do not add manual commits to this branch; open a "
            "separate PR or update the release source branch instead."
        ),
    )


def write_outputs(
    sync: FinishReleaseSync,
    github_output_path: Path,
    pr_body_path: Path,
) -> None:
    with github_output_path.open("a", encoding="utf-8", newline="\n") as github_output:
        github_output.write(f"target_base={sync.target_base}\n")
        github_output.write(f"branch_name={sync.branch_name}\n")
        github_output.write(f"pr_title={sync.pr_title}\n")

    with pr_body_path.open("w", encoding="utf-8", newline="\n") as pr_body_file:
        pr_body_file.write(sync.pr_body)


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Build finish-release sync branch and PR metadata."
    )
    parser.add_argument("version_number")
    parser.add_argument("release_base_ref")
    parser.add_argument("--github-output", required=True, type=Path)
    parser.add_argument("--pr-body-file", required=True, type=Path)
    args = parser.parse_args(argv)

    sync = build_finish_release_sync(args.version_number, args.release_base_ref)
    write_outputs(sync, args.github_output, args.pr_body_file)


if __name__ == "__main__":
    main()
