name: Setup project environment
description: Setup the project environment

inputs:
  node:
    description: Setup node and install root node modules
    default: false
    required: false
  subprojects:
    description: Setup node and install root and subproject node modules (overrides `node` input)
    default: false
    required: false
  brew:
    description: Setup Homebrew
    default: false
    required: false
  ios:
    description: Setup xcode and install dependencies (overrides `brew` input)
    default: false
    required: false
  java:
    description: Setup Java and Gradle cache
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Set up Java
      if: ${{ inputs.java == 'true' }}
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Gradle cache
      if: ${{ inputs.java == 'true' }}
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/development' }}

    - name: Setup node and npm registry
      if: ${{ inputs.node == 'true' || inputs.subprojects == 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'
        cache: 'yarn'

    - name: Install node_modules
      if: ${{ inputs.node == 'true' || inputs.subprojects == 'true' }}
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Install node_modules (example/) and generate native projects
      if: ${{ inputs.subprojects == 'true' }}
      shell: bash
      run: |
        yarn install --frozen-lockfile --cwd example
        yarn prebuild --clean --no-install --cwd example

    - name: Install node_modules (integration_test/)
      if: ${{ inputs.subprojects == 'true' }}
      shell: bash
      run: |
        yarn install --frozen-lockfile --cwd integration_test
        yarn prebuild --clean --no-install --cwd integration_test

    - uses: maxim-lobanov/setup-xcode@v1
      if: ${{ inputs.ios == 'true' }}
      with:
        xcode-version: '15.4'

    - name: Install dependencies
      if: ${{ inputs.ios == 'true' || inputs.brew == 'true' }}
      shell: bash
      run: brew bundle install
