#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$(uname -m)" = arm64 ]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

yarn lint-staged

if [ "$(uname)" = Darwin ]; then
    swiftlint lint --strict
fi
